export const NATIONALITIES = {
  de: [
    { v: 'deutsch', l: 'Deutsch' }, { v: 'österreichisch', l: 'Österreichisch' }, { v: 'schweizerisch', l: 'Schweizerisch' }, { v: '---', l: '───────────' },
    { v: 'albanisch', l: 'Albanisch' }, { v: 'amerikanisch', l: 'Amerikanisch' }, { v: 'australisch', l: 'Australisch' }, { v: 'belgisch', l: 'Belgisch' }, { v: 'bosnisch', l: 'Bosnisch' }, { v: 'brasilianisch', l: 'Brasilianisch' }, { v: 'britisch', l: 'Britisch' }, { v: 'bulgarisch', l: 'Bulgarisch' }, { v: 'chinesisch', l: 'Chinesisch' }, { v: 'dänisch', l: 'Dänisch' }, { v: 'estnisch', l: 'Estnisch' }, { v: 'finnisch', l: 'Finnisch' }, { v: 'französisch', l: 'Französisch' }, { v: 'georgisch', l: 'Georgisch' }, { v: 'griechisch', l: 'Griechisch' }, { v: 'indisch', l: 'Indisch' }, { v: 'iranisch', l: 'Iranisch' }, { v: 'irakisch', l: 'Irakisch' }, { v: 'irisch', l: 'Irisch' }, { v: 'isländisch', l: 'Isländisch' }, { v: 'israelisch', l: 'Israelisch' }, { v: 'italienisch', l: 'Italienisch' }, { v: 'japanisch', l: 'Japanisch' }, { v: 'kanadisch', l: 'Kanadisch' }, { v: 'kasachisch', l: 'Kasachisch' }, { v: 'kosovarisch', l: 'Kosovarisch' }, { v: 'koreanisch', l: 'Koreanisch' }, { v: 'kroatisch', l: 'Kroatisch' }, { v: 'kubanisch', l: 'Kubanisch' }, { v: 'lettisch', l: 'Lettisch' }, { v: 'litauisch', l: 'Litauisch' }, { v: 'luxemburgisch', l: 'Luxemburgisch' }, { v: 'marokkanisch', l: 'Marokkanisch' }, { v: 'mazedonisch', l: 'Mazedonisch' }, { v: 'mexikanisch', l: 'Mexikanisch' }, { v: 'moldauisch', l: 'Moldauisch' }, { v: 'montenegrinisch', l: 'Montenegrinisch' }, { v: 'niederländisch', l: 'Niederländisch' }, { v: 'norwegisch', l: 'Norwegisch' }, { v: 'pakistanisch', l: 'Pakistanisch' }, { v: 'polnisch', l: 'Polnisch' }, { v: 'portugiesisch', l: 'Portugiesisch' }, { v: 'rumänisch', l: 'Rumänisch' }, { v: 'russisch', l: 'Russisch' }, { v: 'saudi-arabisch', l: 'Saudi-Arabisch' }, { v: 'schwedisch', l: 'Schwedisch' }, { v: 'serbisch', l: 'Serbisch' }, { v: 'slowakisch', l: 'Slowakisch' }, { v: 'slowenisch', l: 'Slowenisch' }, { v: 'spanisch', l: 'Spanisch' }, { v: 'syrisch', l: 'Syrisch' }, { v: 'thailändisch', l: 'Thailändisch' }, { v: 'tschechisch', l: 'Tschechisch' }, { v: 'tunesisch', l: 'Tunesisch' }, { v: 'türkisch', l: 'Türkisch' }, { v: 'ukrainisch', l: 'Ukrainisch' }, { v: 'ungarisch', l: 'Ungarisch' }, { v: 'vietnamesisch', l: 'Vietnamesisch' },
  ],
  en: [
    { v: 'german', l: 'German' }, { v: 'austrian', l: 'Austrian' }, { v: 'swiss', l: 'Swiss' }, { v: '---', l: '───────────' },
    { v: 'albanian', l: 'Albanian' }, { v: 'american', l: 'American' }, { v: 'australian', l: 'Australian' }, { v: 'belgian', l: 'Belgian' }, { v: 'bosnian', l: 'Bosnian' }, { v: 'brazilian', l: 'Brazilian' }, { v: 'british', l: 'British' }, { v: 'bulgarian', l: 'Bulgarian' }, { v: 'canadian', l: 'Canadian' }, { v: 'chinese', l: 'Chinese' }, { v: 'croatian', l: 'Croatian' }, { v: 'cuban', l: 'Cuban' }, { v: 'czech', l: 'Czech' }, { v: 'danish', l: 'Danish' }, { v: 'dutch', l: 'Dutch' }, { v: 'estonian', l: 'Estonian' }, { v: 'finnish', l: 'Finnish' }, { v: 'french', l: 'French' }, { v: 'georgian', l: 'Georgian' }, { v: 'greek', l: 'Greek' }, { v: 'hungarian', l: 'Hungarian' }, { v: 'icelandic', l: 'Icelandic' }, { v: 'indian', l: 'Indian' }, { v: 'iranian', l: 'Iranian' }, { v: 'iraqi', l: 'Iraqi' }, { v: 'irish', l: 'Irish' }, { v: 'israeli', l: 'Israeli' }, { v: 'italian', l: 'Italian' }, { v: 'japanese', l: 'Japanese' }, { v: 'kazakh', l: 'Kazakh' }, { v: 'korean', l: 'Korean' }, { v: 'kosovar', l: 'Kosovar' }, { v: 'latvian', l: 'Latvian' }, { v: 'lithuanian', l: 'Lithuanian' }, { v: 'luxembourgish', l: 'Luxembourgish' }, { v: 'macedonian', l: 'Macedonian' }, { v: 'mexican', l: 'Mexican' }, { v: 'moldovan', l: 'Moldovan' }, { v: 'montenegrin', l: 'Montenegrin' }, { v: 'moroccan', l: 'Moroccan' }, { v: 'norwegian', l: 'Norwegian' }, { v: 'pakistani', l: 'Pakistani' }, { v: 'polish', l: 'Polish' }, { v: 'portuguese', l: 'Portuguese' }, { v: 'romanian', l: 'Romanian' }, { v: 'russian', l: 'Russian' }, { v: 'saudi', l: 'Saudi Arabian' }, { v: 'serbian', l: 'Serbian' }, { v: 'slovak', l: 'Slovak' }, { v: 'slovenian', l: 'Slovenian' }, { v: 'spanish', l: 'Spanish' }, { v: 'swedish', l: 'Swedish' }, { v: 'syrian', l: 'Syrian' }, { v: 'thai', l: 'Thai' }, { v: 'tunisian', l: 'Tunisian' }, { v: 'turkish', l: 'Turkish' }, { v: 'ukrainian', l: 'Ukrainian' }, { v: 'vietnamese', l: 'Vietnamese' },
  ],
}

export const PHONE_CODES = [
  { code: '+49', l: 'Deutschland +49' }, { code: '+43', l: 'Österreich +43' }, { code: '+41', l: 'Schweiz +41' }, { code: '---', l: '───────────' },
  { code: '+1', l: 'USA/Kanada +1' }, { code: '+7', l: 'Russland +7' }, { code: '+20', l: 'Ägypten +20' }, { code: '+27', l: 'Südafrika +27' }, { code: '+30', l: 'Griechenland +30' }, { code: '+31', l: 'Niederlande +31' }, { code: '+32', l: 'Belgien +32' }, { code: '+33', l: 'Frankreich +33' }, { code: '+34', l: 'Spanien +34' }, { code: '+36', l: 'Ungarn +36' }, { code: '+39', l: 'Italien +39' }, { code: '+40', l: 'Rumänien +40' }, { code: '+44', l: 'UK +44' }, { code: '+45', l: 'Dänemark +45' }, { code: '+46', l: 'Schweden +46' }, { code: '+47', l: 'Norwegen +47' }, { code: '+48', l: 'Polen +48' }, { code: '+55', l: 'Brasilien +55' }, { code: '+81', l: 'Japan +81' }, { code: '+82', l: 'Südkorea +82' }, { code: '+86', l: 'China +86' }, { code: '+90', l: 'Türkei +90' }, { code: '+91', l: 'Indien +91' }, { code: '+351', l: 'Portugal +351' }, { code: '+352', l: 'Luxemburg +352' }, { code: '+353', l: 'Irland +353' }, { code: '+358', l: 'Finnland +358' }, { code: '+380', l: 'Ukraine +380' }, { code: '+381', l: 'Serbien +381' }, { code: '+385', l: 'Kroatien +385' }, { code: '+386', l: 'Slowenien +386' }, { code: '+387', l: 'Bosnien +387' }, { code: '+420', l: 'Tschechien +420' }, { code: '+421', l: 'Slowakei +421' }, { code: '+966', l: 'Saudi-Arabien +966' }, { code: '+971', l: 'VAE +971' }, { code: '+972', l: 'Israel +972' },
]
